### ISSUE TITLE
Milestone tracking: Initial release

### ISSUE THREAD

**Issue by Xenomega** [crytic/medusa#101]
We have communicated high level tasks on other platforms, but as we wrap this up, the tasks we want to complete for this week can be more granularly found below.

Technical PRs:
- [x] Add an option to ignore testing dynamically deployed contracts (so medusa behaves like echidna) (#102)
- [x] Save call sequences that failed tests + replay all corpus call sequences in the fuzzer on startup to trigger the same failures (#104)
- [x] Add execution traces to call sequences (#105)
- [x] CI should produce build artifacts to simplify releases (#106)
- [ ] Coverage reports (if time permits) (#111)

Pre-release tasks:
- [x] This repository's wiki needs to be updated, as it has not been since december.
- [x] `medusa-geth`'s repository needs to be prepared to go public.
  - [X] `medusa-geth` README.md must be updated.
  - [x] This repository needs to be updated to use `medusa-geth` through `go.mod` at a pinned version after it goes public, and the submodules need to be removed.
  - [ ] #110 can then be merged without errors (presumably)
- [x] A release should be cut, with the previous release deleted, as this is not the version number we'll actually start at.

Initially planned goals for the week that not make the cut, due to re-scoping and prioritizing (ala Gustavo's feedback):
- Begin to introduce a high level testing API with the aim of later supporting Go interface generation for contracts and adding a test harness for them, so we can write tests in Go more akin to truffle, hardhat, or foundry.
  - At some point, the ABI API will be good to replace here, as it will clean up all of our code and support this goal better. The go-ethereum ABI API's limitations are being stretched thin.
