### ISSUE TITLE
Milestone tracking: Post-release

### ISSUE THREAD

**Issue by Xenomega** [crytic/medusa#115]
Future prospects for `medusa` will be undergoing discussion. Discussions will be had surrounding needs and priorities for different tasks. A kick off point for some of these should consider the following.

Smaller effort:
- [ ] Periodically generating calls to view methods in call sequences, to increase coverage (#55)
- [x] Allow auto-completion within bash/sh (#66, **PR**: #79)
- [ ] Revisiting constructor arguments within the project config to lower complexity and allow for multiple deployments of the same contract to be referenced.

Medium effort:
- [ ] Value shrinking within call sequences (#136)

Larger effort:
- [ ] Replacement of go-ethereum's ABI API (#63)
- [ ] High level testing API: A front end testing suite with consideration for Go interface generation for Solidity smart contracts. Building a testing harness around this that plugs into medusa will allow for complex contract deployments, simplification of testing provider code (assertion, property, others), capabilities to write complex custom testing logic with ease, custom cheat code integration, and more. This will inherently tell us where we should invest into API improvements to make querying of complex data easier, and help us standardize our Go API. (#51)
  - [x] Merging `optimization` mode code that uses this new API (#71, **PR**: #75)
  
Once this is agreed upon, we can create the formal GitHub milestone.

**Comment by anishnaik** [comment]
Closing - we will track milestones on medusa's project page
